- name: Creating ec2 instances and updating r53
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-08e9a23d01ec385fb
    zone_id: "AKIA4LBEIRKJTVI5436R"  # AWS zone id which we created in IAM
    domine_name: rajkumardaws.space
    instances:
    - mongodb
    - redis
    - mysql
    - rabbitmq
    
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
      name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output
  
  # - name: print the ec2_output
  #   ansible.builtin.debug:
  #     msg: "{{ ec2_output }}"

  # - name: print public_ip
  #   ansible.builtin.debug: 
  #     msg: "{{ item.instances[0].public_ip_address }}"
  #   loop: "{{ ec2_output.results }}"

  # - name: print private_ip
  #   ansible.builtin.debug: 
  #     msg: "{{ item.instances[0].private_ip_address }}"
  #   loop: "{{ ec2_output.results }}"
  - name: create route53 record
    amazon.aws.route53:
      state: present
      zone: "{{ domine_name }}"
      record: "{{ item.item }}.{{ domine_name }}"  #mongodb.rajkumardaws.space
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      overwrite: true
    loop: "{{ ec2_output.results }}"


