- name: setup frontend server
  hosts: frontend
  become: yes
  tasks:
  - name: disable default nginx
    ansible.builtin.command: dnf module disable nginx -y

  - name: enable nginx 1.24
    ansible.builtin.command: dnf module enable nginx:1.24 -y

  - name: install nginx
    ansible.builtin.command: dnf install nginx -yes
  
  - name: remove default html directory
    ansible.builtin.file:
      state: absent
      path: /usr/share/nginx/html/
  
  - name: create html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: directory
  - name: download frontend application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip

  - name: unzip the application file
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /usr/share/nginx/html/
      remote_src: yes

  - name: delete defauilt nginx conf
    ansible.builtin.file:
      state: absent
      path: /etc/nginx/nginx.conf
  
  - name: copy nginx conf file
    ansible.builtin.copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
  
  - name: restart the nginx
    ansible.builtin.service:
      state: restarted
      enabled: yes