- name: setup payment server
  hosts: payment
  become: yes
  tasks:
  - name: install python package
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
    - python3
    - gcc
    - python3-devel
  - name: adding user
    ansible.builtin.user:
      user: roboshop
      comment: roboshop user
      system: true
      shell: /sbin/nologin
      home: /app
  - name: create a directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create a directory
    ansible.builtin.file:
      state: directory
      path: /app
  
  - name: Delete payment file
    ansible.builtin.file:
      path: /tmp/payment.zip
      state: absent

  - name: download payment application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip
      dest: /tmp/payment.zip

  - name: unzip the application file
    ansible.builtin.unarchive:
      src: /tmp/payment.zip
      dest: /app
      remote_src: yes
  
  - name: install dipendencies
    ansible.builtin.pip:
      requirements: requirements.txt
      executable: 3.9
    args:
      chdir: /app
  - name: copy payment service file
    ansible.builtin.copy:
      scr: payment.service
      dest: /etc/systemd/system/payment.service
  
