- name: setup user server
  hosts: user
  become: yes
  tasks:
  - name: disable the default nodejs
    ansible.builtin.command: dnf module disable nodejs -y
  - name: enable nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y
  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present
  - name: create user
    ansible.builtin.user:
      user: roboshop
      comment: Roboshop system user
      system: true
      shell: /sbin/nologin
      home: /app
  
  - name: remove app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create a directory
    ansible.builtin.file:
      state: directory
      path: /app
  
  - name: Delete user file
    ansible.builtin.file:
      path: /tmp/user.zip
      state: absent

  - name: download user application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
      dest: /tmp/user.zip

  - name: unzip the application file
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes
  - name: install dipendencies
    community.general.npm:
      path: /app

  - name: copy the user service file
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service
  
  - name: daemon reload enable and start
    ansible.builtin.systemd_service:
      name: user
      enabled: true
      state: started
      daemon_reload: true